AR-19993 replace deprecating constructor
pathmatics/MongoLinqPlusPlus pull request #22
Opened 2023-04-05 02:40 UTC by morisamashinka

https://yieldmetrics.atlassian.net/browse/AR-19993

2023-04-05 02:41 UTC, morisamashinka commented
![image](https://user-images.githubusercontent.com/11896469/229967429-f4bf289a-a43a-4451-96d9-8bdeb9124c2f.png)
All test passed

2023-04-07 17:09 UTC, sdcarpenter requested changes

2023-04-07 17:09 UTC, sdcarpenter commented on Src/MongoLinqPlusPlus/Extensions.cs
> +        public static ObjectId GenerateNewIdWithAssigningRandomBytes(DateTime timestamp, string manuallyAssignRandomBytesHexString)
What if we did something like this (Linqpad Script):
```
void Main()
{
	var date = new DateTime(2023, 1, 1);
	
	MakeRandoDateObjectId(date, new byte[] { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0 }).Dump();
	new ObjectId(date, 0, 0, 0).Dump();

	MakeRandoDateObjectId(date, new byte[] { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }).Dump();
	new ObjectId(date, 16777215, -1, 16777215).Dump();

}

// You can define other methods, fields, classes and namespaces here
private static ObjectId MakeRandoDateObjectId(DateTime date, byte[] random)
{
	var newObjId = ObjectId.GenerateNewId(date).ToByteArray();
	Array.Copy(random, 0, newObjId, newObjId.Length - 8, 8);
	return new ObjectId(newObjId);
}
```

2023-04-07 18:09 UTC, sdcarpenter approved these changes
Approved with a tiny nit

2023-04-07 18:09 UTC, sdcarpenter commented on Src/MongoLinqPlusPlus/Pipeline.cs
> +                    //var comparisonValueAsObjectIdMin = new ObjectId(comparisonValue, 0, 0, 0);
Tiny nit, lets delete these commented out lines

2023-04-08 02:14 UTC, merged